
export const catalogo = [
    {   id: 1, titulo: "Rocket League", 
        categoria: "Deportes/Acción", 
        anio: 2015, destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/e4e4005042cf598805d581754fe9256f.jpg",
        descripcion:" Es un videojuego deportivo de ritmo rápido que combina fútbol con coches teledirigidos propulsados por cohetes. El objetivo es marcar goles en la portería rival usando los vehículos para golpear un balón gigante en canchas tipo arena. Se juega principalmente en equipos (1v1, 2v2, 3v3) y destaca por su física, acrobacias aéreas y alta competitividad."
    },
    {   id: 2, titulo: "Warframe", 
        categoria: "Shooter/RPG", 
        anio: 2013, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/dfaa42f6026dd1bc8a76797fc0d191ce.jpg",
        descripcion:" Es un shooter de acción cooperativo en tercera persona ambientado en un futuro lejano, donde los jugadores controlan a los Tenno, antiguos guerreros que despiertan de un sueño criogénico para pilotar armaduras biomecánicas (Warframes) y luchar contra facciones enemigas como los Grineer y Corpus por el dominio del Sistema Origen."
    },
    {   id: 3, 
        titulo: "Jujutsu Kaisen", 
        categoria: "Anime/Acción", 
        anio: 2020, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/1d3a76c27dacd39359bcd75132f1b3c0.jpg",
        descripcion:" Es un juego de lucha de acción 2c2 (arena fighter). Basado en el popular manga/anime. Narra la historia de Yuji Itadori, un estudiante con fuerza física excepcional que se une a una organización secreta de hechiceros para combatir maldiciones (seres monstruosos nacidos de emociones negativas humanas). Tras comerse un dedo maldito para proteger a sus amigos, se convierte en el huésped de Ryomen Sukuna, el Rey de las Maldiciones."
    },
    {   id: 4, 
        titulo: "Hollow Knight", 
        categoria: "Aventura/Indie", 
        anio: 2017, destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/d18c832e8c956b4ef8b92862e6bf470d.jpg",
        descripcion:" Este juego indie sorprendió a críticos y jugadores por su narrativa y diseño magistral, su desafiante jugabilidad y su rica atmósfera. Cuenta la historia del Caballero, en su búsqueda para descubrir los secretos del largamente abandonado reino de Hallownest, cuyas profundidades atraen a los aventureros y valientes con la promesa de tesoros o la respuesta a misterios antiguos."
    },
    {   id: 5, 
        titulo: "Shingeki no Kyojin", 
        categoria: "Anime/Drama", 
        anio: 2013, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/3b3cf80e38c5ad19b29a3e34d49224e7.jpg",
        descripcion:" Se basan en la historia de Hajime Isayama, donde Eren Jaeger y sus compañeros luchan contra titanes devoradores de hombres tras la caída de las murallas. Controlas a personajes del anime utilizando el equipo de maniobras tridimensionales para combatir y cortar partes del cuerpo de titanes gigantes, protegiendo a la humanidad."
    },
    {   id: 6, 
        titulo: "Minecraft", 
        categoria: "Supervivencia", 
        anio: 2011, destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/a73027901f88055aaa0fd1a9e25d36c7.jpg",
        descripcion:" Es un videojuego de tipo sandbox (mundo abierto) de construcción y supervivencia, conocido como Legos digitales. Los jugadores exploran un mundo infinito generado por bloques, recolectan materiales y construyen estructuras sin objetivos obligatorios, fomentando la creatividad y libertad total."
    },
    {   id: 7, 
        titulo: "Boku no Hero Academia", 
        categoria: "Anime/Acción", anio: 2016, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/a7302790.jpg",
        descripcion:" Son títulos de acción y lucha en 3D basados en el anime/manga, donde los jugadores utilizan dones (superpoderes) únicos para combatir en equipos de 3v3 o en formato battle royale, enfrentando a héroes contra villanos en escenarios destruibles."
    },
    {   id: 8, 
        titulo: "Elden Ring", 
        categoria: "RPG/Acción", 
        anio: 2022, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/fc980c0530a7e79d16f6894e5e98df9e.jpg",
        descripcion:" Destaca por su desafiante jugabilidad, exploración libre y una inmersiva atmósfera de fantasía oscura. La historia de Elden Ring gira principalmente en torno a Marika la Eterna, una mujer Numen de la Tierra de las Sombras, que escaparía de su destino para construir y destruir la Orden Dorada . Sin embargo, la historia no comienza ahí, y muchos personajes desempeñan un papel importante."
    },
    {   id: 9, 
        titulo: "Nanatsu no Taizai", 
        categoria: "Anime/Aventura", 
        anio: 2014, destacado: false, 
        imagen: "https://static.wikia.nocookie.net/nanatsu-no-taizai/images/9/9a/Kamigari_no_gekirin_poster.png/revision/latest?cb=20200509224954&path-prefix=es",
        descripcion:" Basado en el anime homónimo, centrado en explorar el continente de Britania. La orden de caballeros que da nombre a la serie los siete pecados capitales (七つの大罪 Nanatsu no Taizai) se compone de siete individuos destacados, reunidos para formar la primera línea de defensa contra amenazas destructivas y cada uno es llamado como algún pecado capital, por algún crimen que cometieron en el pasado."
    },
    {   id: 10, 
        titulo: "Stardew Valley", 
        categoria: "Simulación/Indie", 
        anio: 2016, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/19e2a40db4e1365c35a66e97de3783a5.jpg",
        descripcion:" "
    },
    {   id: 11, 
        titulo: "Kimetsu no Yaiba", 
        categoria: "Anime/Acción", 
        anio: 2019, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/49414050f81ee1f644f745fe1a9e099c.jpg",
        descripcion:" "
    },
    {   id: 12, 
        titulo: "Cyberpunk 2077", 
        categoria: "RPG/Mundo Abierto", 
        anio: 2020, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/f39b781760a403dedaa05587e8889c1a.jpg",
        descripcion:" "
    },
    {   id: 13, 
        titulo: "Death Note", 
        categoria: "Anime/Misterio", 
        anio: 2006, destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/6278a917f19213013188be0c57c12d44.jpg",
        descripcion:" "
    },
    {   id: 14, 
        titulo: "Red Dead Redemption 2", 
        categoria: "Acción/Mundo Abierto", 
        anio: 2018, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/22774e7dbd2a3030e3e0c0b7381dee3e.jpg",
        descripcion:" "
    },
    {   id: 15, 
        titulo: "One Piece", 
        categoria: "Anime/Aventura", 
        anio: 1999, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/60f443092e3c67d5b9c076f303dd60f2.jpg",
        descripcion:" "
    },
    {   id: 16, 
        titulo: "Hades", 
        categoria: "Roguelike/Indie", 
        anio: 2020, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/bfe339860b048949369fc6945cea504d.jpg",
        descripcion:" "
    },
    {   id: 17, 
        titulo: "Naruto Shippuden", 
        categoria: "Anime/Acción", 
        anio: 2007, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/c9266a8821bad0d69092e6781da02930.jpg",
        descripcion:" "
    },
    {   id: 18, 
        titulo: "The Legend of Zelda: Breath of the Wild", 
        categoria: "Aventura", 
        anio: 2017, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/121b81f7d167ca2c24fdab4f044048f8.jpg",
        descripcion:" "
    },
    {   id: 19, 
        titulo: "Fullmetal Alchemist: Brotherhood", 
        categoria: "Anime/Aventura", 
        anio: 2009, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/d79cbab8118661999861724ea55e91ed.jpg",
        descripcion:" "
    },
    {   id: 20, 
        titulo: "God of War", 
        categoria: "Acción/Aventura", 
        anio: 2018, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/368b80128d9e529adf93f7ce84dfaca0.jpg",
        descripcion:" "
    },
    {   id: 21, 
        titulo: "Persona 5 Royal", 
        categoria: "JRPG", 
        anio: 2019, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/78b22a52a1e53b0d2e27e6b40569793a.jpg",
        descripcion:" "
    },
    {   id: 22, 
        titulo: "Hunter x Hunter", 
        categoria: "Anime/Aventura", 
        anio: 2011, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/f19a0748c84a047db01b3fb04749a4ff.jpg",
        descripcion:" "
    },
    {   id: 23, 
        titulo: "League of Legends", 
        categoria: "MOBA", 
        anio: 2009, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/8e65aff4b74febf52c314c22e34c2d32.jpg",
        descripcion:" "
    },
    {   id: 24, 
        titulo: "Valorant", 
        categoria: "Shooter Táctico", 
        anio: 2020, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/b46469c5851be7facec604ceeef9aaaf.jpg",
        descripcion:" "
    },
    {   id: 25, 
        titulo: "Steins;Gate", 
        categoria: "Anime/Ciencia Ficción", 
        anio: 2011, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/adc5d80116b5ba140342824e4e2db411.jpg",
        descripcion:" "
    },
    {   id: 26, 
        titulo: "The Witcher 3: Wild Hunt", 
        categoria: "RPG/Aventura", 
        anio: 2015, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/2f87d717bf556321774d1b4975d2e1c1.jpg",
        descripcion:" "
    },
    {   id: 27, 
        titulo: "Dragon Ball Z", 
        categoria: "Anime/Acción", 
        anio: 1989, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/1975072956057c9fa1f4f44dc9d85237.jpg",
        descripcion:" "
    },
    {   id: 28, 
        titulo: "Celeste", 
        categoria: "Plataformas/Indie", 
        anio: 2018, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/41ed419ab4a0d14a54f9c09526c03ccd.jpg",
        descripcion:" "
    },
    {   id: 29, 
        titulo: "Portal 2", 
        categoria: "Puzzles", 
        anio: 2011, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/f27159c8f16ed644c45ba8598d7dd975.jpg",
        descripcion:" "
    },
    {   id: 30, 
        titulo: "Neon Genesis Evangelion", 
        categoria: "Anime/Mecha", 
        anio: 1995, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/05aeda337ba7bba2dc62ebce8acf2f5d.jpg",
        descripcion:" "
    },
    {   id: 31, 
        titulo: "Apex Legends", 
        categoria: "Battle Royale", 
        anio: 2019, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/0d7a3aef18b1eb97e70a5148e2a2646f.jpg",
        descripcion:" "
    },
    {   id: 32, 
        titulo: "Baldur's Gate 3", 
        categoria: "RPG/Estrategia", 
        anio: 2023, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/b122b82883a834cbcec5c2d2f5c0585c.jpg",
        descripcion:" "
    },
    {   id: 33, 
        titulo: "Bloodborne", 
        categoria: "RPG/Acción", 
        anio: 2015, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/366398b0e15b65afaa427ce5cc94ca9a.jpg",
        descripcion:" "
    },
    {   id: 34, 
        titulo: "Cowboy Bebop", 
        categoria: "Anime/Ciencia Ficción", 
        anio: 1998, 
        destacado: true, 
        imagen: "https://cdn2.steamgriddb.com/thumb/69faf30d3eea4b066add1e0059e58781.jpg",
        descripcion:" "
    },
    {   id: 35, 
        titulo: "Terraria", 
        categoria: "Supervivencia/Indie", 
        anio: 2011, 
        destacado: false, 
        imagen: "https://cdn2.steamgriddb.com/thumb/9ef7f9b81c2532880cfe5cf53f0c906d.jpg",
        descripcion:" "
    }
];